Draft.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -114,35 +114,35 @@ jobs:
       - name: _true
         shell: bash
         run: |
-          ./_true | sudo -n tee ./_local/_true.log
+          ./_true | sudo -n tee ./_local/_true.log && exit ${PIPESTATUS[0]}
       - name: _false
         shell: bash
         run: |
-          ! ./_false | sudo -n tee ./_local/_false.log
+          ! ./_false | sudo -n tee ./_local/_false.log && exit ${PIPESTATUS[0]}
       - name: _create_ubDistBuild-create
         shell: bash
         run: |
-          ./_create_ubDistBuild-create | sudo -n tee ./_local/_create_ubDistBuild-create.log
+          ./_create_ubDistBuild-create | sudo -n tee ./_local/_create_ubDistBuild-create.log && exit ${PIPESTATUS[0]}
       - name: _create_ubDistBuild-rotten_install
         shell: bash
         run: |
-          ./_create_ubDistBuild-rotten_install | sudo -n tee ./_local/_create_ubDistBuild-rotten_install.log
+          ./_create_ubDistBuild-rotten_install | sudo -n tee ./_local/_create_ubDistBuild-rotten_install.log && exit ${PIPESTATUS[0]}
       - name: _chroot_test
         shell: bash
         run: |
-          ./_chroot_test | sudo -n tee ./_local/_chroot_test.log
+          ./_chroot_test | sudo -n tee ./_local/_chroot_test.log && exit ${PIPESTATUS[0]}
       - name: _create_ubDistBuild-bootOnce
         shell: bash
         run: |
-          ./_create_ubDistBuild-bootOnce | sudo -n tee ./_local/_create_ubDistBuild-bootOnce.log
+          ./_create_ubDistBuild-bootOnce | sudo -n tee ./_local/_create_ubDistBuild-bootOnce.log && exit ${PIPESTATUS[0]}
       - name: _create_ubDistBuild-rotten_install-core
         shell: bash
         run: |
-          ./_create_ubDistBuild-rotten_install-core | sudo -n tee ./_create_ubDistBuild-rotten_install-core.log
+          ./_create_ubDistBuild-rotten_install-core | sudo -n tee ./_create_ubDistBuild-rotten_install-core.log && exit ${PIPESTATUS[0]}
       - name: _create_ubDistBuild-install-ubDistBuild
         shell: bash
         run: |
-          ./_create_ubDistBuild-install-ubDistBuild | sudo -n tee ./_create_ubDistBuild-install-ubDistBuild.log
+          ./_create_ubDistBuild-install-ubDistBuild | sudo -n tee ./_create_ubDistBuild-install-ubDistBuild.log && exit ${PIPESTATUS[0]}
       #- name: _create_ubDistBuild-bootOnce
         #shell: bash
         #run: |
@@ -150,11 +150,11 @@ jobs:
       - name: _package_ubDistBuild_image
         shell: bash
         run: |
-          ./_package_ubDistBuild_image | sudo -n tee ./_local/_package_ubDistBuild_image.log
+          ./_package_ubDistBuild_image | sudo -n tee ./_local/_package_ubDistBuild_image.log && exit ${PIPESTATUS[0]}
       - name: _ubDistBuild_split
         shell: bash
         run: |
-          ./ubiquitous_bash.sh _ubDistBuild_split | sudo -n tee ./_lib/_ubDistBuild_split.log
+          ./ubiquitous_bash.sh _ubDistBuild_split | sudo -n tee ./_lib/_ubDistBuild_split.log && exit ${PIPESTATUS[0]}
         timeout-minutes: 355
       - name: release! core
         uses: softprops/action-gh-release@v1
@@ -248,21 +248,21 @@ jobs:
           name: build
           files: |
             ./_local/package_image.tar.xz.part11
-      - name: _croc_ubDistBuild_image_out
-        shell: bash
-        run: |
-          ./ubiquitous_bash.sh _croc_ubDistBuild_image_out | sudo -n tee ./_lib/_croc_ubDistBuild_image_out.log
-        timeout-minutes: 355
+      #- name: _croc_ubDistBuild_image_out
+        #shell: bash
+        #run: |
+          #./ubiquitous_bash.sh _croc_ubDistBuild_image_out | sudo -n tee ./_lib/_croc_ubDistBuild_image_out.log
+        #timeout-minutes: 355
       - name: _assessment
         shell: bash
         run: |
-          ./_assessment | sudo -n tee ./_local/_assessment.log
-      - name: Setup tmate session
-        if: ${{ failure() }}
-        uses: mxschmitt/action-tmate@v3
-        # ssh -i <path-to-key> <tmate-connection-string>
-        with:
-          limit-access-to-actor: true
-        timeout-minutes: 25
+          ./_assessment | sudo -n tee ./_local/_assessment.log && exit ${PIPESTATUS[0]}
+      #- name: Setup tmate session
+        #if: ${{ failure() }}
+        #uses: mxschmitt/action-tmate@v3
+        ## ssh -i <path-to-key> <tmate-connection-string>
+        #with:
+          #limit-access-to-actor: true
+        #timeout-minutes: 25
 
 
