Draft.

diff --git a/.github/workflows/experiment.yml b/.github/workflows/experiment.yml
--- a/.github/workflows/experiment.yml
+++ b/.github/workflows/experiment.yml
@@ -335,9 +335,10 @@ jobs:
         run: |
           ./ubiquitous_bash.sh _openChRoot
           #echo '/root/ubiquitous_bash.sh _wait_rootLock_OTHER'
-          #( ./ubiquitous_bash.sh _chroot crontab -l ; echo '@reboot sleep 35 ; /_rootGrab.sh _wait_rootLock ; /root/_get_nvidia.sh _wait_rootLock ; mkdir -p /media/tmp ; mount -o compress=zstd:2 /dev/sdb /media/tmp ; true > /media/tmp/_run-crontab ; true > /var/log/_run-crontab.log ; poweroff' ) | ./ubiquitous_bash.sh _chroot crontab '-'
-          #( ./ubiquitous_bash.sh _chroot crontab -l ; echo '@reboot /usr/bin/mkdir -p /media/tmp ; /usr/bin/mount -o compress=zstd:2 /dev/sda /media/tmp ; cp -a /home/user/ubDistBuild /media/tmp/ ; /bin/sudo -n -u user /media/tmp/ubDistBuild/ubiquitous_bash.sh _revert-fromLive > /media/tmp/_revert-fromLive.log ; /bin/true > /media/tmp/_run-crontab.log ; /bin/true > /var/log/_run-crontab.log ; /usr/sbin/poweroff ; /sbin/poweroff ; poweroff' ) | ./ubiquitous_bash.sh _chroot crontab '-'
-          ( ./ubiquitous_bash.sh _chroot crontab -l ; echo '@reboot /usr/bin/mkdir -p /media/tmp ; /usr/bin/mount -o compress=zstd:2 /dev/sda /media/tmp ; cp -a /home/user/ubDistBuild /media/tmp/ ; /bin/true > /media/tmp/_run-crontab.log ; /bin/true > /var/log/_run-crontab.log ; /usr/sbin/poweroff ; /sbin/poweroff ; poweroff' ) | ./ubiquitous_bash.sh _chroot crontab '-'
+          #( ./ubiquitous_bash.sh _chroot crontab -l ; echo '@reboot /bin/true uk4uPhB6 ; sleep 35 ; /_rootGrab.sh _wait_rootLock ; /root/_get_nvidia.sh _wait_rootLock ; mkdir -p /media/tmp ; mount -o compress=zstd:2 /dev/sdb /media/tmp ; true > /media/tmp/_run-crontab ; true > /var/log/_run-crontab.log ; poweroff' ) | ./ubiquitous_bash.sh _chroot crontab '-'
+          #( ./ubiquitous_bash.sh _chroot crontab -l ; echo '@reboot /bin/true uk4uPhB6 ; /usr/bin/mkdir -p /media/tmp ; /usr/bin/mount -o compress=zstd:2 /dev/sda /media/tmp ; cp -a /home/user/ubDistBuild /media/tmp/ ; /bin/true > /media/tmp/_run-crontab.log ; /bin/true > /var/log/_run-crontab.log ; /usr/sbin/poweroff ; /sbin/poweroff ; poweroff' ) | ./ubiquitous_bash.sh _chroot crontab '-'
+          ( ./ubiquitous_bash.sh _chroot crontab -l ; echo '@reboot /bin/true uk4uPhB6 ; /usr/bin/mkdir -p /media/tmp ; /usr/bin/mount -o compress=zstd:2 /dev/sda /media/tmp ; cp -a /home/user/ubDistBuild /media/tmp/ ; /bin/sudo -n -u user /media/tmp/ubDistBuild/ubiquitous_bash.sh _revert-fromLive > /media/tmp/_revert-fromLive.log ; /bin/true > /media/tmp/_run-crontab.log ; /bin/true > /var/log/_run-crontab.log ; /usr/sbin/poweroff ; /sbin/poweroff ; poweroff' ) | ./ubiquitous_bash.sh _chroot crontab '-'
+          
           ./ubiquitous_bash.sh _chroot crontab -l
           ./ubiquitous_bash.sh _closeChRoot
 
@@ -434,7 +435,7 @@ jobs:
 
 
 
-      # ### ##### -->   qemu
+      # ### ##### -->   qemu-fromLive
       #_qemu_system_x86_64 -nographic -usb -smp 4 -device usb-tablet -device qxl-vga -machine accel=kvm -bios /usr/share/OVMF/OVMF_CODE.fd -drive format=raw,file=/home/runner/work/ubDistBuild/ubDistBuild/_local/vm.img -drive file=/home/runner/work/ubDistBuild/ubDistBuild/v_uid/htg/htg.iso,media=cdrom -boot d -m 1664 -net nic,model=rtl8139 -net user,restrict=n
       - name: Force KVM group perms
         if: ${{ github.event.inputs.runnerName == 'ubuntu-latest-m' }}
@@ -530,9 +531,9 @@ jobs:
 
             if ( [[ "$currentIterationWait" -le 55 ]] && [[ $(bc <<< "$currentIterationWait % 5") == 0 ]] ) || [[ $(bc <<< "$currentIterationWait % 30") == 0 ]]
             then
-              #xwd -root -silent | convert xwd:- png:./_local/analysis/screenshots/qemu-"$currentIterationWait".png
-              xwd -root -silent | convert xwd:- -quality 35 jpg:./_local/analysis/screenshots/qemu-"$currentIterationWait".jpg
-              jp2a --background=dark --colors --width=280 ./_local/analysis/screenshots/qemu-"$currentIterationWait".jpg
+              #xwd -root -silent | convert xwd:- png:./_local/analysis/screenshots/qemu-01-"$currentIterationWait".png
+              xwd -root -silent | convert xwd:- -quality 35 jpg:./_local/analysis/screenshots/qemu-01-"$currentIterationWait".jpg
+              jp2a --background=dark --colors --width=280 ./_local/analysis/screenshots/qemu-01-"$currentIterationWait".jpg
             fi
 
             let currentIterationWait=currentIterationWait+1
@@ -541,20 +542,23 @@ jobs:
           [[ "$currentIterationWait" -ge "$currentIterationMax" ]] && echo 'bad: fail: run: poweroff' && currentExitStatus=1
           
           exit "$currentExitStatus"
-
-
-
           
       - name: artifacts
         uses: actions/upload-artifact@v3
         with:
-          name: analysis-screenshots
+          name: analysis-screenshots-10-fromLive
           path: |
             ./_local/analysis/screenshots/*
 
 
 
       # ### ##### -->   mount/umount -t btrfs ./_local/cache.img ./_local/cache_fs
+      - name: _rm
+        shell: bash
+        run: |
+          ./ubiquitous_bash.sh _package_rm || true
+          rm -f ./_local/vm.img || true
+
       - name: _export
         shell: bash
         run: |
@@ -562,7 +566,197 @@ jobs:
           mkdir -p ./_local/cache_fs
           sudo -n mount -t btrfs ./_local/cache.img ./_local/cache_fs
           ls ./_local/cache_fs
+          sudo -n dd if=./_local/cache_fs/ubDistBuild/_local/vm.img bs=1M | dd of=./_local/vm.img bs=1M
+          
+      - name: artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: analysis-log-10-fromLive
+          path: |
+            ./_local/cache_fs/*.log
 
+      - name: umount
+        shell: bash
+        run: |
+          sudo -n umount ./_local/cache_fs
+
+
+
+
+
+
+
+          
+      # ### ##### -->   _openChRoot/_closeChRoot   -->   echo ' sleep 35 ; poweroff ' | crontab
+      - name: _run-crontab
+        shell: bash
+        run: |
+          ./ubiquitous_bash.sh _openChRoot
+          #echo '/root/ubiquitous_bash.sh _wait_rootLock_OTHER'
+
+          ( ./ubiquitous_bash.sh _chroot crontab -l | /bin/grep -v uk4uPhB6 ; /bin/sleep 35 ; echo '@reboot /bin/true uk4uPhB6 ; /usr/bin/mkdir -p /media/tmp ; /usr/bin/mount -o compress=zstd:2 /dev/sdb /media/tmp ; cp -a /home/user/ubDistBuild /media/tmp/ ; /bin/sudo -n -u user ls / > /media/tmp/_ls-fromRevert.log ; /bin/true > /media/tmp/_run-crontab.log ; /bin/true > /var/log/_run-crontab.log ; /usr/sbin/poweroff ; /sbin/poweroff ; poweroff' ) | ./ubiquitous_bash.sh _chroot crontab '-'
+          
+          ./ubiquitous_bash.sh _chroot crontab -l
+          ./ubiquitous_bash.sh _closeChRoot
+
+
+
+
+
+
+
+
+
+
+
+
+
+      # ### ##### -->   qemu-fromRevert
+      #_qemu_system_x86_64 -nographic -usb -smp 4 -device usb-tablet -device qxl-vga -machine accel=kvm -bios /usr/share/OVMF/OVMF_CODE.fd -drive format=raw,file=/home/runner/work/ubDistBuild/ubDistBuild/_local/vm.img -drive file=/home/runner/work/ubDistBuild/ubDistBuild/v_uid/htg/htg.iso,media=cdrom -boot d -m 1664 -net nic,model=rtl8139 -net user,restrict=n
+      - name: Force KVM group perms
+        if: ${{ github.event.inputs.runnerName == 'ubuntu-latest-m' }}
+        shell: bash
+        run: |
+          sudo -n ls -l /dev/kvm
+          sudo -n ls -l /dev/kvm*
+          sudo -n chown -R $USER:docker /dev/kvm
+          sudo -n chmod 664 /dev/kvm
+          echo
+          #grep --color svm /proc/cpuinfo || true
+          #grep --color vmx /proc/cpuinfo || true
+          sudo -n lsmod | grep kvm
+          ls -l /dev/kvm
+          ls -l /dev/kvm*
+          echo $USER
+          groups
+          echo
+      - name: qemu-fromRevert
+        shell: bash
+        continue-on-error: true
+        timeout-minutes: 355
+        run: |
+          export skimfast=${{ inputs.skimfast }}
+          echo skimfast $skimfast
+          export qemuNoKVM=${{ inputs.qemuNoKVM }}
+          echo qemuNoKVM $qemuNoKVM
+          echo
+          qemuArgs+=(-usb -smp $(nproc) -device usb-tablet -device qxl-vga)
+          #[[ "$qemuHeadless" == "true" ]] && qemuArgs+=(-nographic)
+          if ./ubiquitous_bash.sh _testQEMU_hostArch_x64_hardwarevt
+          then
+            # Apparently, qemu kvm, can be unreliable if nested (eg. within VMWare Workstation VM).
+            if [[ "$qemuNoKVM" == "true" ]] || [[ "$qemuNoKVM" != "false" ]]
+            then
+              _messagePlain_good 'ignored: kvm'
+            else
+              qemuArgs+=(-machine accel=kvm)
+            fi
+          else
+            echo 'missing: kvm'
+          fi
+          [[ -e /usr/share/OVMF/OVMF_CODE.fd ]] && qemuArgs+=(-bios /usr/share/OVMF/OVMF_CODE.fd)
+          qemuUserArgs+=(-drive format=raw,file=./_local/vm.img)
+          #qemuUserArgs+=(-drive file=./v_uid/htg/htg.iso,media=cdrom)
+          #qemuUserArgs+=(-drive file=./_local/vm-live.iso,media=cdrom)
+          qemuUserArgs+=(-drive format=raw,file=./_local/cache.img)
+          qemuUserArgs+=(-boot c)
+          #qemuUserArgs+=(-boot d)
+          qemuUserArgs+=(-m "6144")
+          qemuUserArgs+=(-net nic,model=rtl8139 -net user,restrict=n)
+          qemuArgs+=("${qemuSpecialArgs[@]}" "${qemuUserArgs[@]}")
+
+          Xvfb :30 > /dev/null 2>&1 &
+          sleep 1
+          export DISPLAY=:30
+
+          echo qemu-system-x86_64 "${qemuArgs[@]}"
+          qemu-system-x86_64 "${qemuArgs[@]}" &
+          currentPID=$!
+
+          currentExitStatus=0
+
+          mkdir -p ./_local/analysis/screenshots
+          currentIterationWait=0
+          currentIterationMax=360
+          ./ubiquitous_bash.sh _testQEMU_hostArch_x64_hardwarevt && currentIterationMax=3200 || true
+          while [[ "$currentIterationWait" -lt "$currentIterationMax" ]] && ( pgrep qemu-system > /dev/null 2>&1 || pgrep qemu > /dev/null 2>&1 || ps -p "$currentPID" > /dev/null 2>&1 )
+          do
+            sleep 1
+
+            echo
+            echo
+            echo
+            echo currentIterationWait="$currentIterationWait"
+            echo
+
+
+            mkdir -p ./_local/cache_fs
+            sudo -n mount -t btrfs -o ro ./_local/cache.img ./_local/cache_fs
+
+            echo 'ls ./_local/cache_fs'
+            sudo -n ls ./_local/cache_fs
+            echo
+
+            echo 'cat ./_local/cache_fs/_revert-fromRevert.log'
+            sudo -n cat ./_local/cache_fs/_revert-fromRevert.log || true
+            echo
+
+            sudo -n umount ./_local/cache_fs
+
+
+
+            if ( [[ "$currentIterationWait" -le 55 ]] && [[ $(bc <<< "$currentIterationWait % 5") == 0 ]] ) || [[ $(bc <<< "$currentIterationWait % 30") == 0 ]]
+            then
+              xwd -root -silent | convert xwd:- -quality 35 jpg:./_local/analysis/screenshots/qemu-20-fromRevert-"$currentIterationWait".jpg
+              jp2a --background=dark --colors --width=280 ./_local/analysis/screenshots/qemu-20-fromRevert-"$currentIterationWait".jpg
+            fi
+
+            let currentIterationWait=currentIterationWait+1
+          done
+          echo 'currentIterationWait='"$currentIterationWait"
+          [[ "$currentIterationWait" -ge "$currentIterationMax" ]] && echo 'bad: fail: run: poweroff' && currentExitStatus=1
+          
+          exit "$currentExitStatus"
+          
+      - name: artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: analysis-screenshots-20-fromRevert
+          path: |
+            ./_local/analysis/screenshots/*
+
+
+
+      # ### ##### -->   mount/umount -t btrfs ./_local/cache.img ./_local/cache_fs
+      - name: _rm
+        shell: bash
+        run: |
+          ./ubiquitous_bash.sh _package_rm || true
+          rm -f ./_local/vm.img || true
+      - name: _export
+        shell: bash
+        run: |
+          lsmod | grep loop || true
+          mkdir -p ./_local/cache_fs
+          sudo -n mount -t btrfs ./_local/cache.img ./_local/cache_fs
+          ls ./_local/cache_fs
+          sudo -n dd if=./_local/cache_fs/ubDistBuild/_local/vm.img bs=1M | dd of=./_local/vm.img bs=1M
+          
+      - name: artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: analysis-log-20-fromRevert
+          path: |
+            ./_local/cache_fs/*.log
+
+
+
+
+
+
+
+
+            
 
 
 
@@ -585,6 +779,7 @@ jobs:
 
 
       # ### ##### -->   PASS/FAIL (from logs)
+
       - name: check
         shell: bash
         run: |
@@ -592,14 +787,8 @@ jobs:
           #sudo -n mount -t btrfs ./_local/cache.img ./_local/cache_fs
           ls ./_local/cache_fs
           [[ -e ./_local/cache_fs/_run-crontab.log ]]
-
-
-      - name: artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: analysis-screenshots
-          path: |
-            ./_local/cache_fs/*.log
+          [[ -e ./_local/cache_fs/_ls_fromRevert.log ]]
+          [[ -e ./_local/cache_fs/_revert-fromLive.log ]]
 
 
 
