Draft.

diff --git a/.github/workflows/experiment.yml b/.github/workflows/experiment.yml
--- a/.github/workflows/experiment.yml
+++ b/.github/workflows/experiment.yml
@@ -189,6 +189,7 @@ jobs:
           git clone --depth 1 --recursive https://github.com/mirage335-colossus/ubiquitous_bash.git
           cd ubiquitous_bash
           ./_setupUbiquitous.bat
+      
       - name: _getMinimal_cloud
         shell: bash
         run: |
@@ -202,29 +203,31 @@ jobs:
       - uses: actions/checkout@v2
         with:
           submodules: recursive
-      - name: _getMinimal_cloud
-        shell: bash
-        run: |
-          ! ./ubiquitous_bash.sh _getMinimal_cloud && exit 1
-          true
-          #! sudo -n apt-get -y clean && exit 1
-          df -h
-          df -h /
-        timeout-minutes: 355
-      # For VBoxManage for _convert . Otherwise historically not apparently necessary.
-      - name: _getMost_ubuntu22-VBoxManage
-        shell: bash
-        run: |
-          #! ./ubiquitous_bash.sh _getMost && exit 1
+      
+      #- name: _getMinimal_cloud
+        #shell: bash
+        #run: |
+          #! ./ubiquitous_bash.sh _getMinimal_cloud && exit 1
           #true
-          #! sudo -n apt-get -y clean && exit 1
-          #! ./ubiquitous_bash.sh _getMost_debian11_aptSources && exit 1
-          #sudo -n apt-get update
-          #! sudo -n apt-get -d install -y virtualbox-7.0 && exit 1
-          ! sudo -n ./ubiquitous_bash.sh _getMost_ubuntu22-VBoxManage && exit 1
-          df -h
-          df -h /
-        timeout-minutes: 355
+          ##! sudo -n apt-get -y clean && exit 1
+          #df -h
+          #df -h /
+        #timeout-minutes: 355
+      
+      # For VBoxManage for _convert . Otherwise historically not apparently necessary.
+      #- name: _getMost_ubuntu22-VBoxManage
+        #shell: bash
+        #run: |
+          ##! ./ubiquitous_bash.sh _getMost && exit 1
+          ##true
+          ##! sudo -n apt-get -y clean && exit 1
+          ##! ./ubiquitous_bash.sh _getMost_debian11_aptSources && exit 1
+          ##sudo -n apt-get update
+          ##! sudo -n apt-get -d install -y virtualbox-7.0 && exit 1
+          #! sudo -n ./ubiquitous_bash.sh _getMost_ubuntu22-VBoxManage && exit 1
+          #df -h
+          #df -h /
+        #timeout-minutes: 355
       - name: _getMost-xvfb
         shell: bash
         run: |
@@ -260,6 +263,7 @@ jobs:
           current_releaseLabel="${{ inputs.releaseLabel }}"
           #[[ "$current_releaseLabel" == "" ]] && current_releaseLabel="base"
           [[ "$current_releaseLabel" == "" ]] && current_releaseLabel="latest"
+          export FORCE_AXEL=8
           ./ubiquitous_bash.sh _get_vmImg_ubDistBuild "$current_releaseLabel"
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -282,7 +286,8 @@ jobs:
           ./ubiquitous_bash.sh _openChRoot
           #echo '/root/ubiquitous_bash.sh _wait_rootLock_OTHER'
           #( ./ubiquitous_bash.sh _chroot crontab -l ; echo '@reboot sleep 35 ; /_rootGrab.sh _wait_rootLock ; /root/_get_nvidia.sh _wait_rootLock ; mkdir -p /media/tmp ; mount -o compress=zstd:2 /dev/sdb /media/tmp ; true > /media/tmp/_run-crontab ; true > /var/log/_run-crontab.log ; poweroff' ) | ./ubiquitous_bash.sh _chroot crontab '-'
-          ( ./ubiquitous_bash.sh _chroot crontab -l ; echo '@reboot ; poweroff' ) | ./ubiquitous_bash.sh _chroot crontab '-'
+          ( ./ubiquitous_bash.sh _chroot crontab -l ; echo '@reboot poweroff' ) | ./ubiquitous_bash.sh _chroot crontab '-'
+          ./ubiquitous_bash.sh _chroot crontab -l
           ./ubiquitous_bash.sh _closeChRoot
 
 
@@ -296,46 +301,46 @@ jobs:
         run: |
           ./ubiquitous_bash.sh _package_rm
 
-      - name: _fetchAccessories extendedInterface
-        shell: bash
-        run: |
-          cd _local
-          git clone https://github.com/mirage335-colossus/extendedInterface.git
-          cd extendedInterface
-          mkdir -p ../extendedInterface-accessories/integrations/ubcp
-          curl -L -o ../extendedInterface-accessories/integrations/ubcp/package_ubcp-core.7z  $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/mirage335-colossus/ubiquitous_bash/releases" | jq -r ".[] | select(.name == \"internal\") | .assets[] | select(.name == \"package_ubcp-core.7z\") | .browser_download_url" | sort -n -r | head -n1)  
-          ./ubiquitous_bash.sh _build_extendedInterface-fetch | sudo -n tee ../../_lib/_extendedInterface.log && exit ${PIPESTATUS[0]}
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: _fetchAccessories ubDistBuild
-        shell: bash
-        run: |
-          cd _local
-          git clone https://github.com/soaringDistributions/ubDistBuild.git
-          cd ubDistBuild
-          mkdir -p ../ubDistBuild-accessories/integrations/ubcp
-          curl -L -o ../ubDistBuild-accessories/integrations/ubcp/package_ubcp-core.7z  $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/mirage335-colossus/ubiquitous_bash/releases" | jq -r ".[] | select(.name == \"internal\") | .assets[] | select(.name == \"package_ubcp-core.7z\") | .browser_download_url" | sort -n -r | head -n1)  
-          ./ubiquitous_bash.sh _build_ubDistBuild-fetch | sudo -n tee ../../_lib/_ubDistBuild.log && exit ${PIPESTATUS[0]}
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #- name: _fetchAccessories extendedInterface
+        #shell: bash
+        #run: |
+          #cd _local
+          #git clone https://github.com/mirage335-colossus/extendedInterface.git
+          #cd extendedInterface
+          #mkdir -p ../extendedInterface-accessories/integrations/ubcp
+          #curl -L -o ../extendedInterface-accessories/integrations/ubcp/package_ubcp-core.7z  $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/mirage335-colossus/ubiquitous_bash/releases" | jq -r ".[] | select(.name == \"internal\") | .assets[] | select(.name == \"package_ubcp-core.7z\") | .browser_download_url" | sort -n -r | head -n1)  
+          #./ubiquitous_bash.sh _build_extendedInterface-fetch | sudo -n tee ../../_lib/_extendedInterface.log && exit ${PIPESTATUS[0]}
+        #env:
+          #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #- name: _fetchAccessories ubDistBuild
+        #shell: bash
+        #run: |
+          #cd _local
+          #git clone https://github.com/soaringDistributions/ubDistBuild.git
+          #cd ubDistBuild
+          #mkdir -p ../ubDistBuild-accessories/integrations/ubcp
+          #curl -L -o ../ubDistBuild-accessories/integrations/ubcp/package_ubcp-core.7z  $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/mirage335-colossus/ubiquitous_bash/releases" | jq -r ".[] | select(.name == \"internal\") | .assets[] | select(.name == \"package_ubcp-core.7z\") | .browser_download_url" | sort -n -r | head -n1)  
+          #./ubiquitous_bash.sh _build_ubDistBuild-fetch | sudo -n tee ../../_lib/_ubDistBuild.log && exit ${PIPESTATUS[0]}
+        #env:
+          #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
-      - name: _convert-live _create_ubDistBuild_feedAccessories
-        shell: bash
-        run: |
-          export current_diskConstrained="true"
-          ./ubiquitous_bash.sh _convert_rm
-          ./ubiquitous_bash.sh _create_ubDistBuild_feedAccessories | sudo -n tee ./_create_ubDistBuild_feedAccessories.log && exit ${PIPESTATUS[0]}
-          ./ubiquitous_bash.sh _safeRMR ./_local/livefs
-          true
+      #- name: _convert-live _create_ubDistBuild_feedAccessories
+        #shell: bash
+        #run: |
+          #export current_diskConstrained="true"
+          #./ubiquitous_bash.sh _convert_rm
+          #./ubiquitous_bash.sh _create_ubDistBuild_feedAccessories | sudo -n tee ./_create_ubDistBuild_feedAccessories.log && exit ${PIPESTATUS[0]}
+          #./ubiquitous_bash.sh _safeRMR ./_local/livefs
+          #true
       
       # DANGER: GitHub Actions ONLY!
-      - name: _create_ubDistBuild_feedAccessories rm
-        shell: bash
-        run: |
-          rm -rf ../extendedInterface-accessories
-          [[ -e ../extendedInterface-accessories ]] && exit 1 || true
-          rm -rf ../ubDistBuild-accessories
-          [[ -e ../ubDistBuild-accessories ]] && exit 1 || true
+      #- name: _create_ubDistBuild_feedAccessories rm
+        #shell: bash
+        #run: |
+          #rm -rf ../extendedInterface-accessories
+          #[[ -e ../extendedInterface-accessories ]] && exit 1 || true
+          #rm -rf ../ubDistBuild-accessories
+          #[[ -e ../ubDistBuild-accessories ]] && exit 1 || true
       
       # DANGER: GitHub Actions ONLY!
       - name: _fetchAccessories rm
@@ -399,7 +404,7 @@ jobs:
       - name: qemu
         shell: bash
         continue-on-error: true
-        timeout-minutes: 20
+        timeout-minutes: 355
         run: |
           export skimfast=${{ inputs.skimfast }}
           echo skimfast $skimfast
@@ -441,7 +446,8 @@ jobs:
 
           mkdir -p ./_local/analysis/screenshots
           currentIterationWait=0
-          while [[ "$currentIterationWait" -lt 720 ]] && ( pgrep qemu-system > /dev/null 2>&1 || pgrep qemu > /dev/null 2>&1 || ps -p "$currentPID" > /dev/null 2>&1 )
+          currentIterationMax=360
+          while [[ "$currentIterationWait" -lt "$currentIterationMax" ]] && ( pgrep qemu-system > /dev/null 2>&1 || pgrep qemu > /dev/null 2>&1 || ps -p "$currentPID" > /dev/null 2>&1 )
           do
             sleep 1
             [[ "$currentIterationWait" -le 55 ]] && [[ $(bc <<< "$currentIterationWait % 5") == 0 ]] && xwd -root -silent | convert xwd:- png:./_local/analysis/screenshots/qemu-"$currentIterationWait".png
@@ -449,7 +455,7 @@ jobs:
             let currentIterationWait=currentIterationWait+1
           done
           echo currentIterationWait
-          [[ "$currentIterationWait" -ge 720 ]] && echo 'bad: fail: bootdisc: poweroff' && currentExitStatus=1
+          [[ "$currentIterationWait" -ge "$currentIterationMax" ]] && echo 'bad: fail: run: poweroff' && currentExitStatus=1
           
           exit "$currentExitStatus"
 
@@ -459,16 +465,17 @@ jobs:
       - name: artifacts
         uses: actions/upload-artifact@v3
         with:
-          name: analysis
+          name: analysis-screenshots
           path: |
             ./_local/analysis/screenshots/*
 
 
 
       # ### ##### -->   mount/umount -t btrfs ./_local/cache.img ./_local/cache_fs
-      - name: export
+      - name: _export
         shell: bash
         run: |
+          lsmod | grep loop
           mkdir -p ./_local/cache_fs
           mount -t btrfs ./_local/cache.img ./_local/cache_fs
           ls ./_local/cache_fs
