Draft.

diff --git a/.github/workflows/zCustom.yml b/.github/workflows/zCustom.yml
--- a/.github/workflows/zCustom.yml
+++ b/.github/workflows/zCustom.yml
@@ -252,6 +252,7 @@ jobs:
         if: ${{ github.event.inputs.DISABLE_BOOT != 'true' }}
         shell: bash
         run: |
+          #! ./ubiquitous_bash.sh _getMinimal_cloud_ubDistBuild_noBoot && exit 1
           ! ./ubiquitous_bash.sh _getMinimal_cloud && exit 1
           true
           #! sudo -n apt-get -y clean && exit 1
@@ -632,23 +633,23 @@ jobs:
           git clone --depth 1 --recursive https://github.com/mirage335-colossus/ubiquitous_bash.git
           cd ubiquitous_bash
           ./_setupUbiquitous.bat
-      - name: _getMinimal_cloud
-        if : ${{ github.event.inputs.DISABLE_RELEASE == 'false' }}
-        shell: bash
-        run: |
-          ! ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud && exit 1
-          true
-          #! sudo -n apt-get -y clean && exit 1
-          df -h
-          df -h /
-        timeout-minutes: 90
+      #- name: _getMinimal_cloud
+        #if : ${{ github.event.inputs.DISABLE_RELEASE == 'false' || github.event.inputs.DANGERfast_EXPERIMENT != 'true' }}
+        #shell: bash
+        #run: |
+          #! ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud && exit 1
+          #true
+          ##! sudo -n apt-get -y clean && exit 1
+          #df -h
+          #df -h /
+        #timeout-minutes: 90
       - uses: actions/checkout@v3
         with:
           submodules: recursive
       - name: _getMinimal_cloud
         shell: bash
         run: |
-          ! ./ubiquitous_bash.sh _getMinimal_cloud && exit 1
+          ! ./ubiquitous_bash.sh _getMinimal_cloud_ubDistBuild_noBoot && exit 1
           true
           #! sudo -n apt-get -y clean && exit 1
           df -h
@@ -702,13 +703,19 @@ jobs:
           export MANDATORY_HASH="true"
           cd ./_local
           rm -f hash-download.txt
+          if [[ ${{ github.event.inputs.DISABLE_RELEASE }} != true || ${{ github.event.inputs.DANGERfast_EXPERIMENT }} != true ]]
+          then
           ../ubiquitous_bash.sh _wget_githubRelease_join-stdout "$current_releaseOrigin" "$current_releaseLabel" "package_image.tar.flx" 2> /dev/null | tee >(../ubiquitous_bash.sh _get_extract_ubDistBuild-tar --extract ./vm.img --to-stdout | env OPENSSL_CONF="/etc/ssl/openssl_legacy.cnf" openssl dgst -whirlpool -binary | xxd -p -c 256 > hash-download.txt) | ../ubiquitous_bash.sh _get_extract_ubDistBuild
+          else
+          ../ubiquitous_bash.sh _wget_githubRelease_join-stdout "$current_releaseOrigin" "$current_releaseLabel" "package_image.tar.flx" 2> /dev/null | ../ubiquitous_bash.sh _get_extract_ubDistBuild
+          fi
+          true
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       
       - name: _hash_img
-        if : ${{ github.event.inputs.DANGERfast_EXPERIMENT != 'true' }}
+        if : ${{ github.event.inputs.DISABLE_RELEASE != 'true' || github.event.inputs.DANGERfast_EXPERIMENT != 'true' }}
         shell: bash
         run: |
           export skimfast=${{ inputs.skimfast }}
@@ -717,6 +724,7 @@ jobs:
           cat _local/hash-download.txt
 
       - name: fallocate --dig-holes
+        if : ${{ github.event.inputs.DISABLE_RELEASE == 'false' || github.event.inputs.DISABLE_BOOT == 'false' }}
         shell: bash
         run: |
           fallocate --dig-holes ./_local/vm.img
@@ -845,6 +853,7 @@ jobs:
 
 
       - name: _hash_img
+        if : ${{ github.event.inputs.DISABLE_RELEASE != 'true' || github.event.inputs.DANGERfast_EXPERIMENT != 'true' }}
         shell: bash
         run: |
           export skimfast=${{ inputs.skimfast }}
@@ -853,18 +862,21 @@ jobs:
       
 
       - name: fallocate --dig-holes
+        if : ${{ github.event.inputs.DISABLE_RELEASE == 'false' || github.event.inputs.DISABLE_BOOT == 'false' }}
         shell: bash
         run: |
           fallocate --dig-holes ./_local/vm.img
       
       
       - name: _package_ubDistBuild_image
+        if : ${{ github.event.inputs.DISABLE_RELEASE == 'false' || github.event.inputs.DISABLE_BOOT == 'false' }}
         shell: bash
         run: |
           export skimfast=${{ inputs.skimfast }}
           echo $skimfast
           ./ubiquitous_bash.sh _package_ubDistBuild_image | sudo -n tee ./_local/_package_ubDistBuild_image.log && exit ${PIPESTATUS[0]}
       - name: _ubDistBuild_split
+        if : ${{ github.event.inputs.DISABLE_RELEASE == 'false' || github.event.inputs.DISABLE_BOOT == 'false' }}
         shell: bash
         run: |
           ./ubiquitous_bash.sh _ubDistBuild_split | sudo -n tee ./_lib/_ubDistBuild_split.log && exit ${PIPESTATUS[0]}
@@ -877,6 +889,7 @@ jobs:
 
 
       - name: release! package_image
+        if : ${{ github.event.inputs.DISABLE_RELEASE == 'false' || github.event.inputs.DISABLE_BOOT == 'false' }}
         shell: bash
         run: |
           #gh release create ${{ inputs.DANGERfast_EXPERIMENT }}-${{ github.run_id }}-${{ github.run_attempt }} --title build --notes ""
@@ -896,6 +909,7 @@ jobs:
 
 
       - name: release! delete! package_image_before_noBoot
+        if : ${{ github.event.inputs.DISABLE_BOOT == 'false' }}
         shell: bash
         continue-on-error: true
         run: |
@@ -974,6 +988,7 @@ jobs:
 
 
   build-convert-rootfs:
+    if : ${{ github.event.inputs.DISABLE_RELEASE == 'false' }}
     needs: [build, build_release]
     runs-on: ${{ github.event.inputs.DISABLE_ROOTFS != 'false' && 'ubuntu-latest' || github.event.inputs.runnerName == '' && 'ubuntu-latest-m' || github.event.inputs.runnerName }}
     steps:
@@ -1050,7 +1065,7 @@ jobs:
       - name: _getMinimal_cloud
         shell: bash
         run: |
-          ! ./ubiquitous_bash.sh _getMinimal_cloud && exit 1
+          ! ./ubiquitous_bash.sh _getMinimal_cloud_ubDistBuild_noBoot && exit 1
           true
           #! sudo -n apt-get -y clean && exit 1
           df -h
@@ -1184,6 +1199,7 @@ jobs:
 
 
   build-convert-live:
+    if : ${{ github.event.inputs.DISABLE_RELEASE == 'false' }}
     needs: [build, build_release]
     runs-on: ${{ github.event.inputs.runnerName == '' && 'ubuntu-latest-m' || github.event.inputs.runnerName }}
     steps:
@@ -1266,7 +1282,7 @@ jobs:
       - name: _getMinimal_cloud
         shell: bash
         run: |
-          ! ./ubiquitous_bash.sh _getMinimal_cloud && exit 1
+          ! ./ubiquitous_bash.sh _getMinimal_cloud_ubDistBuild_noBoot && exit 1
           true
           #! sudo -n apt-get -y clean && exit 1
           df -h
@@ -1427,6 +1443,7 @@ jobs:
 
 
   build-hash:
+    if : ${{ github.event.inputs.DISABLE_RELEASE != 'true' && github.event.inputs.DANGERfast_EXPERIMENT != 'true' }}
     needs: [build, build-convert-rootfs, build-convert-live]
     runs-on: ubuntu-latest
     #runs-on: ${{ github.event.inputs.runnerName == '' && 'ubuntu-latest' || github.event.inputs.runnerName }}
@@ -1618,44 +1635,88 @@ jobs:
     needs: [build, build_release]
     runs-on: ubuntu-latest
     steps:
-      - name: report! API Rate Limit
-        shell: bash
-        run: |
-          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ""${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/rate_limit
-          #curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit | jq -r ".rate"
+      #- name: report! API Rate Limit
+        #shell: bash
+        #run: |
+          #curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ""${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/rate_limit
+          ##curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit | jq -r ".rate"
       
-      - name: _getCore_ub
-        shell: bash
-        run: |
-          mkdir -p ~/core/infrastructure
-          cd ~/core/infrastructure
-          git clone --depth 1 --recursive https://github.com/mirage335-colossus/ubiquitous_bash.git
-          cd ubiquitous_bash
-          ./_setupUbiquitous.bat
-          ./ubiquitous_bash.sh _custom_splice_opensslConfig
+      #- name: _getCore_ub
+        #shell: bash
+        #run: |
+          #mkdir -p ~/core/infrastructure
+          #cd ~/core/infrastructure
+          ##git clone --depth 1 --recursive https://github.com/mirage335-colossus/ubiquitous_bash.git
+          #git clone --depth 1 https://github.com/mirage335-colossus/ubiquitous_bash.git
+          #cd ubiquitous_bash
+          #./_setupUbiquitous.bat
+          #./ubiquitous_bash.sh _custom_splice_opensslConfig
 
       - uses: actions/checkout@v3
         with:
           fetch-depth: 1
-          submodules: 'recursive'
+          #submodules: 'recursive'
 
-      - name: _getMinimal_cloud
+      #- name: _getMinimal_cloud
+        #shell: bash
+        #run: |
+          #! ./ubiquitous_bash.sh _getMinimal_cloud_ubDistBuild_noBoot && exit 1
+          #true
+          ##! sudo -n apt-get -y clean && exit 1
+          #df -h
+          #df -h /
+        #timeout-minutes: 355
+
+      - name: _getMinimal_cloud-analysis
         shell: bash
         run: |
-          ! ./ubiquitous_bash.sh _getMinimal_cloud && exit 1
-          true
-          #! sudo -n apt-get -y clean && exit 1
-          df -h
-          df -h /
-        timeout-minutes: 355
+          sudo -n apt-get -y install jq gh curl coreutils
       
-      - name: _getMost-aria2
+      #- name: _getMost-aria2
+        #shell: bash
+        #run: |
+          #sudo -n apt-get -y clean
+          #sudo -n apt-get update
+          #sudo -n env DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install --install-recommends -y aria2
+        #timeout-minutes: 355
+
+      - name: report! cronUserReport
         shell: bash
         run: |
-          sudo -n apt-get -y clean
-          sudo -n apt-get update
-          sudo -n env DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install --install-recommends -y aria2
-        timeout-minutes: 355
+          mkdir -p ./_local/analysis
+
+          cd ./_local/analysis
+
+          # Get the list of releases
+          RELEASES=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/"${{ github.repository }}"/releases)
+
+          # Download binReport file for the current release
+          curl -s -H "Authorization: token $GH_TOKEN" -L -o "cronUserReport-$currentReleaseTag" "https://github.com/"${{ github.repository }}"/releases/download/$currentReleaseTag/cronUserReport"
+
+          echo
+          cat ./cronUserReport-$currentReleaseTag
+        env:
+          currentReleaseTag: ${{ inputs.DANGERfast_EXPERIMENT }}-${{ github.run_id }}-${{ github.run_attempt }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: report! cronRootReport
+        shell: bash
+        run: |
+          mkdir -p ./_local/analysis
+
+          cd ./_local/analysis
+
+          # Get the list of releases
+          RELEASES=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/"${{ github.repository }}"/releases)
+
+          # Download binReport file for the current release
+          curl -s -H "Authorization: token $GH_TOKEN" -L -o "cronRootReport-$currentReleaseTag" "https://github.com/"${{ github.repository }}"/releases/download/$currentReleaseTag/cronRootReport"
+
+          echo
+          cat ./cronRootReport-$currentReleaseTag
+        env:
+          currentReleaseTag: ${{ inputs.DANGERfast_EXPERIMENT }}-${{ github.run_id }}-${{ github.run_attempt }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
       - name: analysis! missing-binaries
@@ -1674,36 +1735,45 @@ jobs:
           RELEASES=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/"${{ github.repository }}"/releases)
 
           # Download binReport file for the current release
-          curl -s -H "Authorization: token $GH_TOKEN" -L -o "lsmodReport-$currentReleaseTag" "https://github.com/"${{ github.repository }}"/releases/download/$currentReleaseTag/lsmodReport"
+          #curl -s -H "Authorization: token $GH_TOKEN" -L -o "lsmodReport-$currentReleaseTag" "https://github.com/"${{ github.repository }}"/releases/download/$currentReleaseTag/lsmodReport"
           curl -s -H "Authorization: token $GH_TOKEN" -L -o "binReport-$currentReleaseTag" "https://github.com/"${{ github.repository }}"/releases/download/$currentReleaseTag/binReport"
           curl -s -H "Authorization: token $GH_TOKEN" -L -o "coreReport-$currentReleaseTag" "https://github.com/"${{ github.repository }}"/releases/download/$currentReleaseTag/coreReport"
           curl -s -H "Authorization: token $GH_TOKEN" -L -o "dpkg-$currentReleaseTag" "https://github.com/"${{ github.repository }}"/releases/download/$currentReleaseTag/dpkg"
+          curl -s -H "Authorization: token $GH_TOKEN" -L -o "customReport-$currentReleaseTag" "https://github.com/"${{ github.repository }}"/releases/download/$currentReleaseTag/customReport"
 
           # Loop through each release
+          #local currentIteration
+          currentIteration=0
           #for RELEASE in $(echo "$RELEASES" | jq -r '.[].tag_name' | sort --reverse); do
-          for RELEASE in $(echo "$RELEASES" | jq -r 'sort_by(.published_at) | reverse | .[].tag_name'); do
+          for RELEASE in $(echo "$RELEASES" | jq -r 'sort_by(.published_at) | reverse | .[].tag_name' | head -n 20); do
+
+            currentIteration=$((currentIteration+1))
 
             # Compare the list of binaries in this release to the current release
             if [ "$RELEASE" != "$currentReleaseTag" ]; then
               
               # Download the binReport file for this release
-              curl -s -H "Authorization: token $GH_TOKEN" -L -o "lsmodReport-$RELEASE" "https://github.com/"${{ github.repository }}"/releases/download/$RELEASE/lsmodReport"
-              curl -s -H "Authorization: token $GH_TOKEN" -L -o "binReport-$RELEASE" "https://github.com/"${{ github.repository }}"/releases/download/$RELEASE/binReport"
-              curl -s -H "Authorization: token $GH_TOKEN" -L -o "coreReport-$RELEASE" "https://github.com/"${{ github.repository }}"/releases/download/$RELEASE/coreReport"
+              #[[ "$currentIteration" -lt "5" ]] && curl -s -H "Authorization: token $GH_TOKEN" -L -o "lsmodReport-$RELEASE" "https://github.com/"${{ github.repository }}"/releases/download/$RELEASE/lsmodReport"
+              [[ "$currentIteration" -lt "6" ]] && curl -s -H "Authorization: token $GH_TOKEN" -L -o "binReport-$RELEASE" "https://github.com/"${{ github.repository }}"/releases/download/$RELEASE/binReport"
+              [[ "$currentIteration" -lt "7" ]] && curl -s -H "Authorization: token $GH_TOKEN" -L -o "coreReport-$RELEASE" "https://github.com/"${{ github.repository }}"/releases/download/$RELEASE/coreReport"
               curl -s -H "Authorization: token $GH_TOKEN" -L -o "dpkg-$RELEASE" "https://github.com/"${{ github.repository }}"/releases/download/$RELEASE/dpkg"
+              curl -s -H "Authorization: token $GH_TOKEN" -L -o "customReport-$RELEASE" "https://github.com/"${{ github.repository }}"/releases/download/$RELEASE/customReport"
               
-              echo | tee -a ./missing-lsmodReport
-              echo "Binaries (lsmod) loaded in $RELEASE but not in currentRelease $currentReleaseTag:" | tee -a ./missing-lsmodReport
-              comm -23 <(sort "lsmodReport-$RELEASE") <(sort "lsmodReport-$currentReleaseTag") | tee -a ./missing-lsmodReport
-              echo | tee -a ./missing-binReport
-              echo "Binaries (filesystem) in $RELEASE but not in currentRelease $currentReleaseTag:" | tee -a ./missing-binReport
-              comm -23 <(sort "binReport-$RELEASE") <(sort "binReport-$currentReleaseTag") | tee -a ./missing-binReport
-              echo | tee -a ./missing-coreReport
-              echo "Binaries (core) in $RELEASE but not in currentRelease $currentReleaseTag:" | tee -a ./missing-coreReport
-              comm -23 <(sort "coreReport-$RELEASE" | grep -v '_local/h') <(sort "coreReport-$currentReleaseTag" | grep -v '_local/h') | tee -a ./missing-coreReport
+              #[[ "$currentIteration" -lt "5" ]] && echo | tee -a ./missing-lsmodReport
+              #[[ "$currentIteration" -lt "5" ]] && echo "Binaries (lsmod) loaded in $RELEASE but not in currentRelease $currentReleaseTag:" | tee -a ./missing-lsmodReport
+              #[[ "$currentIteration" -lt "5" ]] && comm -23 <(sort "lsmodReport-$RELEASE") <(sort "lsmodReport-$currentReleaseTag") | tee -a ./missing-lsmodReport
+              [[ "$currentIteration" -lt "6" ]] && echo | tee -a ./missing-binReport
+              [[ "$currentIteration" -lt "6" ]] && echo "Binaries (filesystem) in $RELEASE but not in currentRelease $currentReleaseTag:" | tee -a ./missing-binReport
+              [[ "$currentIteration" -lt "6" ]] && comm -23 <(sort "binReport-$RELEASE") <(sort "binReport-$currentReleaseTag") | tee -a ./missing-binReport
+              [[ "$currentIteration" -lt "7" ]] && echo | tee -a ./missing-coreReport
+              [[ "$currentIteration" -lt "7" ]] && echo "Binaries (core) in $RELEASE but not in currentRelease $currentReleaseTag:" | tee -a ./missing-coreReport
+              [[ "$currentIteration" -lt "7" ]] && comm -23 <(sort "coreReport-$RELEASE" | grep -v '_local/h') <(sort "coreReport-$currentReleaseTag" | grep -v '_local/h') | tee -a ./missing-coreReport
               echo | tee -a ./missing-dpkg
               echo "Binaries (dpkg) in $RELEASE but not in currentRelease $currentReleaseTag:" | tee -a ./missing-dpkg
               comm -23 <(sort "dpkg-$RELEASE") <(sort "dpkg-$currentReleaseTag") | tee -a ./missing-dpkg
+              echo | tee -a ./missing-customReport
+              echo "Binaries (filesystem: custom) in $RELEASE but not in currentRelease $currentReleaseTag:" | tee -a ./missing-customReport
+              comm -23 <(sort "customReport-$RELEASE" | grep -v '_local/h') <(sort "customReport-$currentReleaseTag" | grep -v '_local/h') | tee -a ./missing-customReport
             fi
           done
         env:
@@ -1713,12 +1783,19 @@ jobs:
       - name: release! analysis! missing-binaries
         shell: bash
         run: |
-            gh release upload ${{ inputs.DANGERfast_EXPERIMENT }}-${{ github.run_id }}-${{ github.run_attempt }} ./_local/analysis/missing-lsmodReport
+            #gh release upload ${{ inputs.DANGERfast_EXPERIMENT }}-${{ github.run_id }}-${{ github.run_attempt }} ./_local/analysis/missing-lsmodReport
             gh release upload ${{ inputs.DANGERfast_EXPERIMENT }}-${{ github.run_id }}-${{ github.run_attempt }} ./_local/analysis/missing-binReport
             gh release upload ${{ inputs.DANGERfast_EXPERIMENT }}-${{ github.run_id }}-${{ github.run_attempt }} ./_local/analysis/missing-coreReport
             gh release upload ${{ inputs.DANGERfast_EXPERIMENT }}-${{ github.run_id }}-${{ github.run_attempt }} ./_local/analysis/missing-dpkg
+            gh release upload ${{ inputs.DANGERfast_EXPERIMENT }}-${{ github.run_id }}-${{ github.run_attempt }} ./_local/analysis/missing-customReport
         env:
           GH_TOKEN: ${{ github.token }}
+          
+      - name: report! API Rate Limit
+        shell: bash
+        run: |
+          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ""${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/rate_limit
+          #curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit | jq -r ".rate"
 
 
     
